"""Add is_activate to groups table

Revision ID: 8d38122354bd
Revises: 16bf9942d657
Create Date: 2024-04-05 22:42:19.458092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d38122354bd'
down_revision: Union[str, None] = '16bf9942d657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('is_activate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'is_activate')
    # ### end Alembic commands ###
